import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import Sidebar from "../../../components/LayoutComponents/Sidebar";
import TopNav from "../../../components/LayoutComponents/TopNav";
import { hostelApi } from "../../../api/hostelApi";

type Room = { id: number; name: string; floor?: string; capacity: number; occupied: number; is_active: boolean };
type Hostel = { id: number; name: string; gender: string; warden_name?: string; warden_phone?: string; is_active: boolean; occupied: number; rooms: Room[] };
type Student = { id: number; firstname: string; surname: string; reg_no?: string; email?: string; sex?: string };
type Period = { id: number; name: string; is_current?: boolean };
type Allocation = { id: number; allocated_at: string; student: Student; hostel: { name: string; gender?: string }; room: Room; session?: Period; term?: Period };
type History = { id: number; action: string; reason?: string; created_at: string; student: Student; from_hostel?: { name: string }; from_room?: { name: string }; to_hostel?: { name: string }; to_room?: { name: string }; actor?: Student };
type Dashboard = { hostels: Hostel[]; students: Student[]; allocations: Allocation[]; history: History[]; sessions: Period[]; terms: Period[]; selected_session_id?: number; selected_term_id?: number; summary: { hostels: number; rooms: number; capacity: number; occupied: number } };

const emptyHostel = { name: "", gender: "mixed", warden_name: "", warden_phone: "", address: "" };
const errorMessage = (error: any) => error?.response?.data?.message || Object.values(error?.response?.data?.errors || {}).flat()[0] || "Something went wrong.";
const studentName = (student: Student) => `${student.firstname || ""} ${student.surname || ""}`.trim();

export default function HostelManagementPage() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [data, setData] = useState<Dashboard>({ hostels: [], students: [], allocations: [], history: [], sessions: [], terms: [], summary: { hostels: 0, rooms: 0, capacity: 0, occupied: 0 } });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [hostelForm, setHostelForm] = useState(emptyHostel);
  const [roomForm, setRoomForm] = useState({ hostel_id: "", name: "", floor: "", capacity: 1 });
  const [allocationForm, setAllocationForm] = useState({ student_id: "", hostel_room_id: "", session_id: "", term_id: "", notes: "" });
  const [search, setSearch] = useState("");
  const [sessionFilter, setSessionFilter] = useState(""); const [termFilter, setTermFilter] = useState("");
  const [transfer, setTransfer] = useState({ allocation_id: 0, room_id: "", reason: "" });

  const load = async () => {
    setLoading(true); setError("");
    try { const response = await hostelApi.dashboard({ ...(sessionFilter ? { session_id: sessionFilter } : {}), ...(termFilter ? { term_id: termFilter } : {}) }); setData(response.data); setAllocationForm((form) => ({ ...form, session_id: form.session_id || String(response.data.selected_session_id || ""), term_id: form.term_id || String(response.data.selected_term_id || "") })); }
    catch (err) { setError(String(errorMessage(err))); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [sessionFilter, termFilter]);

  const rooms = useMemo(() => data.hostels.flatMap((hostel) => hostel.rooms.map((room) => ({ ...room, hostel }))), [data.hostels]);
  const availableRooms = rooms.filter((room) => room.is_active && room.hostel.is_active && room.occupied < room.capacity);
  const filtered = data.allocations.filter((item) => `${studentName(item.student)} ${item.student.reg_no || ""} ${item.hostel.name} ${item.room.name}`.toLowerCase().includes(search.toLowerCase()));
  const occupancy = data.summary.capacity ? Math.round((data.summary.occupied / data.summary.capacity) * 100) : 0;

  const run = async (action: () => Promise<unknown>, success: string) => {
    setSaving(true); setError(""); setNotice("");
    try { await action(); setNotice(success); await load(); return true; }
    catch (err) { setError(String(errorMessage(err))); return false; }
    finally { setSaving(false); }
  };
  const createHostel = async (event: FormEvent) => { event.preventDefault(); if (await run(() => hostelApi.createHostel(hostelForm), "Hostel created successfully.")) setHostelForm(emptyHostel); };
  const createRoom = async (event: FormEvent) => { event.preventDefault(); if (await run(() => hostelApi.createRoom(Number(roomForm.hostel_id), roomForm), "Room added successfully.")) setRoomForm({ hostel_id: "", name: "", floor: "", capacity: 1 }); };
  const allocate = async (event: FormEvent) => { event.preventDefault(); if (await run(() => hostelApi.allocate(allocationForm), "Student allocated successfully.")) setAllocationForm((form) => ({ student_id: "", hostel_room_id: "", session_id: form.session_id, term_id: form.term_id, notes: "" })); };
  const editHostel = (hostel: Hostel) => { const name = window.prompt("Hostel name", hostel.name); if (!name) return; const warden_name = window.prompt("Warden name", hostel.warden_name || "") ?? hostel.warden_name; run(() => hostelApi.updateHostel(hostel.id, { name, warden_name }), "Hostel updated."); };
  const editRoom = (room: Room) => { const name = window.prompt("Room name", room.name); if (!name) return; const capacity = Number(window.prompt("Bed capacity", String(room.capacity))); if (!capacity) return; run(() => hostelApi.updateRoom(room.id, { name, capacity }), "Room updated."); };
  const submitTransfer = async () => { if (!transfer.allocation_id || !transfer.room_id || transfer.reason.trim().length < 3) return; if (await run(() => hostelApi.transfer(transfer.allocation_id, Number(transfer.room_id), transfer.reason), "Student transferred successfully.")) setTransfer({ allocation_id: 0, room_id: "", reason: "" }); };
  const exportCsv = () => { const rows = [["Admission No","Student","Gender","Hostel","Room","Session","Term","Allocated"], ...filtered.map(item => [item.student.reg_no||"",studentName(item.student),item.student.sex||"",item.hostel.name,item.room.name,item.session?.name||"",item.term?.name||"",new Date(item.allocated_at).toLocaleDateString()])]; const blob = new Blob([rows.map(row => row.map(value => `"${String(value).replaceAll('"','""')}"`).join(",")).join("\n")], { type: "text/csv" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "hostel-allocations.csv"; link.click(); URL.revokeObjectURL(link.href); };

  return <>
    <style>{`
      .hostel-hero{background:#0f172a;border-radius:16px;padding:32px 36px;position:relative;overflow:hidden;margin:10px 0 22px;border:1px solid rgba(255,255,255,.06)}
      .hostel-hero:before{content:"";position:absolute;inset:0;background-image:radial-gradient(circle,rgba(255,255,255,.045) 1px,transparent 1px);background-size:24px 24px;pointer-events:none}
      .hostel-hero-glow{position:absolute;top:-90px;right:-40px;width:350px;height:350px;border-radius:50%;background:radial-gradient(circle,rgba(201,168,76,.13),transparent 66%)}
      .hostel-hero-inner{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:32px;flex-wrap:wrap}
      .hostel-kicker{display:inline-flex;align-items:center;gap:7px;font-size:11px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:#e8c97a;background:rgba(201,168,76,.1);border:1px solid rgba(201,168,76,.22);border-radius:999px;padding:5px 12px;margin-bottom:14px}
      .hostel-dot{width:6px;height:6px;border-radius:50%;background:#22c55e}.hostel-title{font-family:"Lora",Georgia,serif;font-size:clamp(24px,2.5vw,34px);font-weight:700;color:#fff;line-height:1.1;margin:0 0 9px}.hostel-title em{color:#e8c97a;font-style:italic}
      .hostel-sub{font-size:13.5px;font-weight:300;color:#94a3b8;line-height:1.65;max-width:590px;margin:0}.hostel-hero-stats{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.09);border-radius:12px;padding:18px 22px;min-width:260px}
      .hostel-hero-row{display:flex;justify-content:space-between;gap:28px;padding:7px 0;color:#94a3b8;font-size:12px}.hostel-hero-row+.hostel-hero-row{border-top:1px solid rgba(255,255,255,.07)}.hostel-hero-row strong{font-family:"Lora",serif;color:#fff;font-size:17px}
      .hostel-page .card,.hostel-panel{background:#fff;border:1px solid rgba(5,0,8,.08)!important;border-radius:14px!important;box-shadow:0 8px 24px rgba(5,0,8,.045)!important;overflow:hidden}.hostel-page .card h5,.hostel-panel h5{font-family:"Lora",Georgia,serif;font-weight:700;color:#1a1a2e}.hostel-page .form-label{font-size:12px;font-weight:600;color:#6b5f55}.hostel-page .form-control,.hostel-page .form-select{border-color:#e5ddd3;border-radius:8px;font-size:13px}
      @media(max-width:767.98px){.hostel-hero{padding:25px 22px}.hostel-hero-stats{width:100%}}
    `}</style>
    <TopNav sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} title="Hostel Management" />
    <div className="container-fluid"><div className="row">
      <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
      <main className="col-md-9 col-lg-10 ms-auto db-main hostel-page">
        <div className="hostel-hero"><div className="hostel-hero-glow" /><div className="hostel-hero-inner"><div><div className="hostel-kicker"><span className="hostel-dot" />Accommodation operations</div><h1 className="hostel-title">Hostel <em>Management</em></h1><p className="hostel-sub">Manage buildings, room capacity and student accommodation with live occupancy visibility.</p></div><div className="hostel-hero-stats"><div className="hostel-hero-row"><span>Occupancy rate</span><strong>{occupancy}%</strong></div><div className="hostel-hero-row"><span>Available spaces</span><strong>{Math.max(0, data.summary.capacity - data.summary.occupied)}</strong></div><div className="hostel-hero-row"><span>Active hostels</span><strong>{data.summary.hostels}</strong></div></div></div>
        </div>
        {error && <div className="alert alert-danger">{error}</div>}{notice && <div className="alert alert-success">{notice}</div>}
        <div className="card mb-4"><div className="card-body d-flex flex-wrap align-items-end gap-3"><div><label className="form-label">Academic session</label><select className="form-select" value={sessionFilter} onChange={(e) => setSessionFilter(e.target.value)}><option value="">Current session</option>{data.sessions.map((session) => <option key={session.id} value={session.id}>{session.name}</option>)}</select></div><div><label className="form-label">Term</label><select className="form-select" value={termFilter} onChange={(e) => setTermFilter(e.target.value)}><option value="">All terms</option>{data.terms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</select></div><button className="btn btn-outline-primary ms-auto" onClick={exportCsv} disabled={!filtered.length}><i className="bi bi-download me-2" />Export allocations</button></div></div>
        <div className="row g-3 mb-4">
          {[["Hostels", data.summary.hostels, "bi-buildings", "primary"], ["Rooms", data.summary.rooms, "bi-door-open", "info"], ["Bed capacity", data.summary.capacity, "bi-grid-3x3-gap", "warning"], ["Students housed", data.summary.occupied, "bi-people", "success"]].map(([label, value, icon, color]) =>
            <div className="col-6 col-xl-3" key={String(label)}><div className="card border-0 shadow-sm h-100"><div className="card-body d-flex align-items-center gap-3"><span className={`bg-${color}-subtle text-${color} rounded-3 p-3`}><i className={`bi ${icon} fs-4`} /></span><div><div className="text-muted small">{label}</div><div className="fs-3 fw-bold">{value}</div></div></div></div></div>)}
        </div>
        <div className="row g-4 mb-4">
          <div className="col-xl-4"><div className="card border-0 shadow-sm h-100"><div className="card-header bg-white border-0 pt-4 px-4"><h5 className="mb-1">Add hostel</h5><small className="text-muted">Create an accommodation building.</small></div><form className="card-body px-4" onSubmit={createHostel}>
            <label className="form-label">Hostel name</label><input className="form-control mb-3" required value={hostelForm.name} onChange={(e) => setHostelForm({ ...hostelForm, name: e.target.value })} placeholder="e.g. Mandela Hall" />
            <div className="row g-2 mb-3"><div className="col-5"><label className="form-label">Gender</label><select className="form-select" value={hostelForm.gender} onChange={(e) => setHostelForm({ ...hostelForm, gender: e.target.value })}><option value="mixed">Mixed</option><option value="male">Male</option><option value="female">Female</option></select></div><div className="col-7"><label className="form-label">Warden</label><input className="form-control" value={hostelForm.warden_name} onChange={(e) => setHostelForm({ ...hostelForm, warden_name: e.target.value })} /></div></div>
            <label className="form-label">Warden phone</label><input className="form-control mb-3" value={hostelForm.warden_phone} onChange={(e) => setHostelForm({ ...hostelForm, warden_phone: e.target.value })} /><button className="btn btn-primary w-100" disabled={saving}>Create hostel</button>
          </form></div></div>
          <div className="col-xl-4"><div className="card border-0 shadow-sm h-100"><div className="card-header bg-white border-0 pt-4 px-4"><h5 className="mb-1">Add room</h5><small className="text-muted">Capacity represents available bed spaces.</small></div><form className="card-body px-4" onSubmit={createRoom}>
            <label className="form-label">Hostel</label><select className="form-select mb-3" required value={roomForm.hostel_id} onChange={(e) => setRoomForm({ ...roomForm, hostel_id: e.target.value })}><option value="">Select hostel</option>{data.hostels.filter((h) => h.is_active).map((h) => <option key={h.id} value={h.id}>{h.name}</option>)}</select>
            <div className="row g-2 mb-3"><div className="col-7"><label className="form-label">Room name/number</label><input className="form-control" required value={roomForm.name} onChange={(e) => setRoomForm({ ...roomForm, name: e.target.value })} placeholder="Room 101" /></div><div className="col-5"><label className="form-label">Capacity</label><input className="form-control" type="number" min={1} max={1000} required value={roomForm.capacity} onChange={(e) => setRoomForm({ ...roomForm, capacity: Number(e.target.value) })} /></div></div>
            <label className="form-label">Floor/block</label><input className="form-control mb-3" value={roomForm.floor} onChange={(e) => setRoomForm({ ...roomForm, floor: e.target.value })} placeholder="Ground floor" /><button className="btn btn-primary w-100" disabled={saving || !data.hostels.length}>Add room</button>
          </form></div></div>
          <div className="col-xl-4"><div className="card border-0 shadow-sm h-100"><div className="card-header bg-white border-0 pt-4 px-4"><h5 className="mb-1">Allocate student</h5><small className="text-muted">Only rooms with free spaces are shown.</small></div><form className="card-body px-4" onSubmit={allocate}>
            <label className="form-label">Student</label><select className="form-select mb-3" required value={allocationForm.student_id} onChange={(e) => setAllocationForm({ ...allocationForm, student_id: e.target.value })}><option value="">Select student</option>{data.students.map((s) => <option key={s.id} value={s.id}>{studentName(s)} {s.reg_no ? `(${s.reg_no})` : ""}</option>)}</select>
            <label className="form-label">Room</label><select className="form-select mb-3" required value={allocationForm.hostel_room_id} onChange={(e) => setAllocationForm({ ...allocationForm, hostel_room_id: e.target.value })}><option value="">Select available room</option>{availableRooms.map((r) => <option key={r.id} value={r.id}>{r.hostel.name} · {r.name} ({r.capacity - r.occupied} free)</option>)}</select>
            <div className="row g-2 mb-3"><div className="col-7"><label className="form-label">Session</label><select className="form-select" required value={allocationForm.session_id} onChange={(e) => setAllocationForm({ ...allocationForm, session_id: e.target.value })}>{data.sessions.map((session) => <option key={session.id} value={session.id}>{session.name}</option>)}</select></div><div className="col-5"><label className="form-label">Term</label><select className="form-select" value={allocationForm.term_id} onChange={(e) => setAllocationForm({ ...allocationForm, term_id: e.target.value })}><option value="">All year</option>{data.terms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</select></div></div>
            <label className="form-label">Notes</label><textarea className="form-control mb-3" rows={2} value={allocationForm.notes} onChange={(e) => setAllocationForm({ ...allocationForm, notes: e.target.value })} /><button className="btn btn-primary w-100" disabled={saving || !availableRooms.length}>Allocate student</button>
          </form></div></div>
        </div>
        <div className="card border-0 shadow-sm mb-4"><div className="card-header bg-white border-0 p-4 d-flex flex-wrap justify-content-between gap-3"><div><h5 className="mb-1">Hostels and rooms</h5><small className="text-muted">Live occupancy by room.</small></div></div><div className="card-body pt-0"><div className="row g-3">{data.hostels.map((hostel) => <div className="col-xl-6" key={hostel.id}><div className="border rounded-3 p-3 h-100"><div className="d-flex justify-content-between"><div><h5 className="mb-1">{hostel.name}</h5><small className="text-muted text-capitalize">{hostel.gender} · {hostel.warden_name || "No warden assigned"}</small></div><span className={`badge ${hostel.is_active ? "bg-success-subtle text-success" : "bg-secondary-subtle text-secondary"}`}>{hostel.is_active ? "Active" : "Inactive"}</span></div><div className="row g-2 mt-2">{hostel.rooms.map((room) => <div className="col-sm-6" key={room.id}><div className="bg-light rounded-3 p-3"><div className="d-flex justify-content-between"><strong>{room.name}</strong><span>{room.occupied}/{room.capacity}</span></div><div className="progress mt-2" style={{ height: 6 }}><div className="progress-bar" style={{ width: `${Math.min(100, room.capacity ? room.occupied / room.capacity * 100 : 0)}%` }} /></div><small className="text-muted">{room.floor || "Floor not specified"}</small></div></div>)}{!hostel.rooms.length && <div className="text-muted small">No rooms added yet.</div>}</div></div></div>)}{!loading && !data.hostels.length && <div className="text-center text-muted py-5">Create your first hostel to begin.</div>}</div></div></div>
        <div className="card hostel-panel"><div className="card-header bg-white border-0 p-4 d-flex flex-wrap justify-content-between gap-3"><div><h5 className="mb-1">Current residents</h5><small className="text-muted">Active student allocations.</small></div><input className="form-control" style={{ maxWidth: 300 }} placeholder="Search student or room" value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="table-responsive"><table className="table align-middle mb-0"><thead className="table-light"><tr><th className="ps-4">Student</th><th>Hostel</th><th>Room</th><th>Allocated</th><th className="text-end pe-4">Action</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td className="ps-4"><strong>{studentName(item.student)}</strong><div className="small text-muted">{item.student.reg_no || item.student.email}</div></td><td>{item.hostel.name}</td><td>{item.room.name}</td><td>{new Date(item.allocated_at).toLocaleDateString()}</td><td className="text-end pe-4"><button className="btn btn-sm btn-outline-danger" disabled={saving} onClick={() => window.confirm("Check this student out of the hostel?") && run(() => hostelApi.checkout(item.id), "Student checked out successfully.")}>Check out</button></td></tr>)}{!loading && !filtered.length && <tr><td colSpan={5} className="text-center text-muted py-5">No active hostel allocations found.</td></tr>}</tbody></table></div></div>
        <div className="card mt-4"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Manage accommodation</h5><small className="text-muted">Edit or deactivate hostels and rooms without deleting historical records.</small></div><div className="table-responsive"><table className="table align-middle mb-0"><thead className="table-light"><tr><th className="ps-4">Hostel / room</th><th>Gender / floor</th><th>Capacity</th><th>Status</th><th className="text-end pe-4">Actions</th></tr></thead><tbody>{data.hostels.flatMap((hostel) => [<tr key={`h-${hostel.id}`}><td className="ps-4 fw-bold">{hostel.name}</td><td className="text-capitalize">{hostel.gender}</td><td>{hostel.rooms.reduce((sum, room) => sum + room.capacity, 0)}</td><td>{hostel.is_active ? "Active" : "Inactive"}</td><td className="text-end pe-4"><button className="btn btn-sm btn-outline-primary me-2" onClick={() => editHostel(hostel)}>Edit</button><button className="btn btn-sm btn-outline-secondary" onClick={() => run(() => hostelApi.updateHostel(hostel.id, { is_active: !hostel.is_active }), hostel.is_active ? "Hostel deactivated." : "Hostel activated.")}>{hostel.is_active ? "Deactivate" : "Activate"}</button></td></tr>, ...hostel.rooms.map((room) => <tr key={`r-${room.id}`}><td className="ps-5">↳ {room.name}</td><td>{room.floor || "—"}</td><td>{room.occupied}/{room.capacity}</td><td>{room.is_active ? "Active" : "Inactive"}</td><td className="text-end pe-4"><button className="btn btn-sm btn-outline-primary me-2" onClick={() => editRoom(room)}>Edit</button><button className="btn btn-sm btn-outline-secondary" onClick={() => run(() => hostelApi.updateRoom(room.id, { is_active: !room.is_active }), room.is_active ? "Room deactivated." : "Room activated.")}>{room.is_active ? "Deactivate" : "Activate"}</button></td></tr>)])}</tbody></table></div></div>
        <div className="card mt-4"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Transfer a resident</h5><small className="text-muted">Move an active resident while preserving the allocation history.</small></div><div className="card-body pt-0"><div className="row g-3 align-items-end"><div className="col-md-4"><label className="form-label">Resident</label><select className="form-select" value={transfer.allocation_id || ""} onChange={(e) => setTransfer({ ...transfer, allocation_id: Number(e.target.value) })}><option value="">Select resident</option>{data.allocations.map((item) => <option key={item.id} value={item.id}>{studentName(item.student)} · {item.hostel.name}/{item.room.name}</option>)}</select></div><div className="col-md-3"><label className="form-label">Destination room</label><select className="form-select" value={transfer.room_id} onChange={(e) => setTransfer({ ...transfer, room_id: e.target.value })}><option value="">Select room</option>{availableRooms.map((room) => <option key={room.id} value={room.id}>{room.hostel.name} · {room.name}</option>)}</select></div><div className="col-md-3"><label className="form-label">Reason</label><input className="form-control" value={transfer.reason} onChange={(e) => setTransfer({ ...transfer, reason: e.target.value })} placeholder="Reason for transfer" /></div><div className="col-md-2"><button className="btn btn-primary w-100" disabled={saving || !transfer.allocation_id || !transfer.room_id || transfer.reason.trim().length < 3} onClick={submitTransfer}>Transfer</button></div></div></div></div>
        <div className="card mt-4"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Allocation history</h5><small className="text-muted">Recent allocations, transfers and checkouts.</small></div><div className="table-responsive"><table className="table align-middle mb-0"><thead className="table-light"><tr><th className="ps-4">Student</th><th>Action</th><th>Movement</th><th>Reason</th><th>Date</th></tr></thead><tbody>{data.history.map((event) => <tr key={event.id}><td className="ps-4">{studentName(event.student)}<div className="small text-muted">{event.student.reg_no}</div></td><td className="text-capitalize">{event.action.replaceAll("_", " ")}</td><td>{event.from_hostel?.name ? `${event.from_hostel.name}/${event.from_room?.name || ""} → ` : ""}{event.to_hostel?.name ? `${event.to_hostel.name}/${event.to_room?.name || ""}` : "Checked out"}</td><td>{event.reason || "—"}</td><td>{new Date(event.created_at).toLocaleString()}</td></tr>)}{!data.history.length && <tr><td colSpan={5} className="text-center text-muted py-4">No allocation history yet.</td></tr>}</tbody></table></div></div>
      </main>
    </div></div>
  </>;
}
