import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import Sidebar from "../../../components/LayoutComponents/Sidebar";
import TopNav from "../../../components/LayoutComponents/TopNav";
import { transportApi } from "../../../api/transportApi";

type Student = { id: number; firstname: string; surname: string; reg_no?: string; email?: string };
type Stop = { id: number; name: string; pickup_time?: string; dropoff_time?: string; fee?: string };
type Vehicle = { id: number; name?: string; registration_number: string; capacity: number; occupied: number; driver_name?: string; driver_phone?: string; is_active: boolean };
type Route = { id: number; name: string; start_location?: string; end_location?: string; default_fee?: string; is_active: boolean; passengers: number; stops: Stop[]; vehicles: Vehicle[] };
type Assignment = { id: number; trip_type: string; assigned_at: string; student: Student; route: { name: string }; stop?: { name: string }; vehicle: Vehicle };
type Dashboard = { routes: Route[]; students: Student[]; assignments: Assignment[]; summary: { routes: number; stops: number; vehicles: number; capacity: number; passengers: number } };
const initial: Dashboard = { routes: [], students: [], assignments: [], summary: { routes: 0, stops: 0, vehicles: 0, capacity: 0, passengers: 0 } };
const nameOf = (student: Student) => `${student.firstname || ""} ${student.surname || ""}`.trim();
const messageOf = (error: any) => error?.response?.data?.message || Object.values(error?.response?.data?.errors || {}).flat()[0] || "Something went wrong.";

export default function TransportManagementPage() {
  const [sidebarOpen, setSidebarOpen] = useState(false); const [data, setData] = useState<Dashboard>(initial);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [search, setSearch] = useState("");
  const [routeForm, setRouteForm] = useState({ name: "", start_location: "", end_location: "", default_fee: "" });
  const [vehicleForm, setVehicleForm] = useState({ transport_route_id: "", registration_number: "", name: "", capacity: 1, driver_name: "", driver_phone: "" });
  const [stopForm, setStopForm] = useState({ transport_route_id: "", name: "", pickup_time: "", dropoff_time: "", fee: "" });
  const [assignmentForm, setAssignmentForm] = useState({ student_id: "", transport_vehicle_id: "", transport_stop_id: "", trip_type: "both", notes: "" });
  const load = async () => { setLoading(true); setError(""); try { setData((await transportApi.dashboard()).data); } catch (e) { setError(String(messageOf(e))); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const vehicles = useMemo(() => data.routes.flatMap((route) => route.vehicles.map((vehicle) => ({ ...vehicle, route }))), [data.routes]);
  const selectedVehicle = vehicles.find((vehicle) => vehicle.id === Number(assignmentForm.transport_vehicle_id));
  const stops = selectedVehicle?.route.stops || [];
  const availableVehicles = vehicles.filter((vehicle) => vehicle.is_active && vehicle.route.is_active && vehicle.occupied < vehicle.capacity);
  const occupancy = data.summary.capacity ? Math.round(data.summary.passengers / data.summary.capacity * 100) : 0;
  const assignments = data.assignments.filter((item) => `${nameOf(item.student)} ${item.student.reg_no || ""} ${item.route.name} ${item.vehicle.registration_number}`.toLowerCase().includes(search.toLowerCase()));
  const run = async (action: () => Promise<unknown>, success: string) => { setSaving(true); setError(""); setNotice(""); try { await action(); setNotice(success); await load(); return true; } catch (e) { setError(String(messageOf(e))); return false; } finally { setSaving(false); } };
  const createRoute = async (e: FormEvent) => { e.preventDefault(); if (await run(() => transportApi.createRoute(routeForm), "Route created successfully.")) setRouteForm({ name: "", start_location: "", end_location: "", default_fee: "" }); };
  const createVehicle = async (e: FormEvent) => { e.preventDefault(); if (await run(() => transportApi.createVehicle(vehicleForm), "Vehicle added successfully.")) setVehicleForm({ transport_route_id: "", registration_number: "", name: "", capacity: 1, driver_name: "", driver_phone: "" }); };
  const createStop = async (e: FormEvent) => { e.preventDefault(); if (await run(() => transportApi.createStop(Number(stopForm.transport_route_id), stopForm), "Stop added successfully.")) setStopForm({ transport_route_id: "", name: "", pickup_time: "", dropoff_time: "", fee: "" }); };
  const assign = async (e: FormEvent) => { e.preventDefault(); if (await run(() => transportApi.assign(assignmentForm), "Student assigned successfully.")) setAssignmentForm({ student_id: "", transport_vehicle_id: "", transport_stop_id: "", trip_type: "both", notes: "" }); };

  return <><style>{`
    .transport-hero{background:#0f172a;border-radius:16px;padding:32px 36px;position:relative;overflow:hidden;margin:10px 0 22px;border:1px solid rgba(255,255,255,.06)}.transport-hero:before{content:"";position:absolute;inset:0;background-image:radial-gradient(circle,rgba(255,255,255,.045) 1px,transparent 1px);background-size:24px 24px}.transport-glow{position:absolute;right:-70px;top:-100px;width:380px;height:380px;border-radius:50%;background:radial-gradient(circle,rgba(201,168,76,.13),transparent 67%)}
    .transport-hero-inner{position:relative;z-index:1;display:flex;align-items:center;justify-content:space-between;gap:30px;flex-wrap:wrap}.transport-kicker{display:inline-flex;align-items:center;gap:7px;font-size:11px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:#e8c97a;background:rgba(201,168,76,.1);border:1px solid rgba(201,168,76,.22);border-radius:999px;padding:5px 12px;margin-bottom:14px}.transport-kicker span{width:6px;height:6px;background:#22c55e;border-radius:50%}
    .transport-title{font-family:"Lora",Georgia,serif;font-size:clamp(24px,2.5vw,34px);font-weight:700;color:#fff;margin:0 0 9px}.transport-title em{color:#e8c97a}.transport-sub{font-size:13.5px;color:#94a3b8;max-width:580px;margin:0;line-height:1.65}.transport-hero-stats{background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.09);border-radius:12px;padding:18px 22px;min-width:260px}.transport-hero-row{display:flex;justify-content:space-between;gap:24px;padding:7px 0;color:#94a3b8;font-size:12px}.transport-hero-row+.transport-hero-row{border-top:1px solid rgba(255,255,255,.07)}.transport-hero-row strong{font-family:"Lora",serif;color:#fff;font-size:17px}
    .transport-page .card{border:1px solid rgba(5,0,8,.08)!important;border-radius:14px!important;box-shadow:0 8px 24px rgba(5,0,8,.045)!important;overflow:hidden}.transport-page .card h5{font-family:"Lora",Georgia,serif;font-weight:700;color:#1a1a2e}.transport-page .form-label{font-size:12px;font-weight:600;color:#6b5f55}.transport-page .form-control,.transport-page .form-select{border-color:#e5ddd3;border-radius:8px;font-size:13px}@media(max-width:767.98px){.transport-hero{padding:25px 22px}.transport-hero-stats{width:100%}}
  `}</style><TopNav sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} title="Transport Management" /><div className="container-fluid"><div className="row"><Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} /><main className="col-md-9 col-lg-10 ms-auto db-main transport-page">
    <div className="transport-hero"><div className="transport-glow" /><div className="transport-hero-inner"><div><div className="transport-kicker"><span />School mobility operations</div><h1 className="transport-title">Transport <em>Management</em></h1><p className="transport-sub">Coordinate routes, stops, vehicles and student transport assignments with live capacity tracking.</p></div><div className="transport-hero-stats"><div className="transport-hero-row"><span>Fleet occupancy</span><strong>{occupancy}%</strong></div><div className="transport-hero-row"><span>Available seats</span><strong>{Math.max(0, data.summary.capacity - data.summary.passengers)}</strong></div><div className="transport-hero-row"><span>Active passengers</span><strong>{data.summary.passengers}</strong></div></div></div></div>
    {error && <div className="alert alert-danger">{error}</div>}{notice && <div className="alert alert-success">{notice}</div>}
    <div className="row g-3 mb-4">{[["Routes",data.summary.routes,"bi-signpost-2","primary"],["Stops",data.summary.stops,"bi-geo-alt","info"],["Vehicles",data.summary.vehicles,"bi-bus-front","warning"],["Passengers",data.summary.passengers,"bi-people","success"]].map(([label,value,icon,color])=><div className="col-6 col-xl-3" key={String(label)}><div className="card h-100"><div className="card-body d-flex align-items-center gap-3"><span className={`bg-${color}-subtle text-${color} rounded-3 p-3`}><i className={`bi ${icon} fs-4`} /></span><div><small className="text-muted">{label}</small><div className="fs-3 fw-bold">{value}</div></div></div></div></div>)}</div>
    <div className="row g-4 mb-4"><div className="col-xl-6"><div className="card h-100"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Add route</h5><small className="text-muted">Define a transport corridor and default fee.</small></div><form className="card-body pt-0" onSubmit={createRoute}><label className="form-label">Route name</label><input required className="form-control mb-3" value={routeForm.name} onChange={e=>setRouteForm({...routeForm,name:e.target.value})} placeholder="e.g. Lekki - School" /><div className="row g-2 mb-3"><div className="col-6"><label className="form-label">Start</label><input className="form-control" value={routeForm.start_location} onChange={e=>setRouteForm({...routeForm,start_location:e.target.value})} /></div><div className="col-6"><label className="form-label">End</label><input className="form-control" value={routeForm.end_location} onChange={e=>setRouteForm({...routeForm,end_location:e.target.value})} /></div></div><label className="form-label">Default fee (₦)</label><input type="number" min="0" className="form-control mb-3" value={routeForm.default_fee} onChange={e=>setRouteForm({...routeForm,default_fee:e.target.value})} /><button className="btn btn-primary w-100" disabled={saving}>Create route</button></form></div></div>
    <div className="col-xl-6"><div className="card h-100"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Add vehicle</h5><small className="text-muted">Assign a vehicle and driver to a route.</small></div><form className="card-body pt-0" onSubmit={createVehicle}><label className="form-label">Route</label><select required className="form-select mb-3" value={vehicleForm.transport_route_id} onChange={e=>setVehicleForm({...vehicleForm,transport_route_id:e.target.value})}><option value="">Select route</option>{data.routes.map(route=><option key={route.id} value={route.id}>{route.name}</option>)}</select><div className="row g-2 mb-3"><div className="col-7"><label className="form-label">Registration number</label><input required className="form-control" value={vehicleForm.registration_number} onChange={e=>setVehicleForm({...vehicleForm,registration_number:e.target.value})} /></div><div className="col-5"><label className="form-label">Seats</label><input required type="number" min="1" max="500" className="form-control" value={vehicleForm.capacity} onChange={e=>setVehicleForm({...vehicleForm,capacity:Number(e.target.value)})} /></div></div><div className="row g-2 mb-3"><div className="col-6"><label className="form-label">Driver</label><input className="form-control" value={vehicleForm.driver_name} onChange={e=>setVehicleForm({...vehicleForm,driver_name:e.target.value})} /></div><div className="col-6"><label className="form-label">Driver phone</label><input className="form-control" value={vehicleForm.driver_phone} onChange={e=>setVehicleForm({...vehicleForm,driver_phone:e.target.value})} /></div></div><button className="btn btn-primary w-100" disabled={saving||!data.routes.length}>Add vehicle</button></form></div></div></div>
    <div className="row g-4 mb-4"><div className="col-xl-6"><div className="card h-100"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Add route stop</h5><small className="text-muted">Set pickup/drop-off points and times.</small></div><form className="card-body pt-0" onSubmit={createStop}><label className="form-label">Route</label><select required className="form-select mb-3" value={stopForm.transport_route_id} onChange={e=>setStopForm({...stopForm,transport_route_id:e.target.value})}><option value="">Select route</option>{data.routes.map(route=><option key={route.id} value={route.id}>{route.name}</option>)}</select><label className="form-label">Stop name</label><input required className="form-control mb-3" value={stopForm.name} onChange={e=>setStopForm({...stopForm,name:e.target.value})} /><div className="row g-2 mb-3"><div className="col-6"><label className="form-label">Pickup time</label><input type="time" className="form-control" value={stopForm.pickup_time} onChange={e=>setStopForm({...stopForm,pickup_time:e.target.value})} /></div><div className="col-6"><label className="form-label">Stop fee (₦)</label><input type="number" min="0" className="form-control" value={stopForm.fee} onChange={e=>setStopForm({...stopForm,fee:e.target.value})} /></div></div><button className="btn btn-primary w-100" disabled={saving||!data.routes.length}>Add stop</button></form></div></div>
    <div className="col-xl-6"><div className="card h-100"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Assign student</h5><small className="text-muted">Only vehicles with free seats are shown.</small></div><form className="card-body pt-0" onSubmit={assign}><label className="form-label">Student</label><select required className="form-select mb-3" value={assignmentForm.student_id} onChange={e=>setAssignmentForm({...assignmentForm,student_id:e.target.value})}><option value="">Select student</option>{data.students.map(student=><option key={student.id} value={student.id}>{nameOf(student)} {student.reg_no?`(${student.reg_no})`:""}</option>)}</select><label className="form-label">Vehicle and route</label><select required className="form-select mb-3" value={assignmentForm.transport_vehicle_id} onChange={e=>setAssignmentForm({...assignmentForm,transport_vehicle_id:e.target.value,transport_stop_id:""})}><option value="">Select vehicle</option>{availableVehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.route.name} · {vehicle.registration_number} ({vehicle.capacity-vehicle.occupied} seats)</option>)}</select><div className="row g-2 mb-3"><div className="col-7"><label className="form-label">Stop</label><select className="form-select" value={assignmentForm.transport_stop_id} onChange={e=>setAssignmentForm({...assignmentForm,transport_stop_id:e.target.value})}><option value="">No specific stop</option>{stops.map(stop=><option key={stop.id} value={stop.id}>{stop.name}</option>)}</select></div><div className="col-5"><label className="form-label">Trip</label><select className="form-select" value={assignmentForm.trip_type} onChange={e=>setAssignmentForm({...assignmentForm,trip_type:e.target.value})}><option value="both">Both ways</option><option value="pickup">Pickup only</option><option value="dropoff">Drop-off only</option></select></div></div><button className="btn btn-primary w-100" disabled={saving||!availableVehicles.length}>Assign student</button></form></div></div></div>
    <div className="card mb-4"><div className="card-header bg-white border-0 p-4"><h5 className="mb-1">Routes and fleet</h5><small className="text-muted">Live route, stop and vehicle occupancy.</small></div><div className="card-body pt-0"><div className="row g-3">{data.routes.map(route=><div className="col-xl-6" key={route.id}><div className="border rounded-3 p-3 h-100"><div className="d-flex justify-content-between"><div><strong>{route.name}</strong><div className="small text-muted">{route.start_location||"Start not set"} → {route.end_location||"School"}</div></div><span className="badge bg-success-subtle text-success">{route.passengers} passengers</span></div><div className="small text-muted mt-3 mb-2">{route.stops.length} stops</div>{route.vehicles.map(vehicle=><div className="bg-light rounded-3 p-2 mb-2" key={vehicle.id}><div className="d-flex justify-content-between"><span><i className="bi bi-bus-front me-2" />{vehicle.name||vehicle.registration_number}</span><strong>{vehicle.occupied}/{vehicle.capacity}</strong></div><small className="text-muted">{vehicle.driver_name||"No driver assigned"}</small></div>)}{!route.vehicles.length&&<small className="text-muted">No vehicles assigned.</small>}</div></div>)}{!loading&&!data.routes.length&&<div className="text-center text-muted py-5">Create your first transport route to begin.</div>}</div></div></div>
    <div className="card"><div className="card-header bg-white border-0 p-4 d-flex flex-wrap justify-content-between gap-3"><div><h5 className="mb-1">Student passengers</h5><small className="text-muted">Current active transport assignments.</small></div><input className="form-control" style={{maxWidth:300}} placeholder="Search student, route or vehicle" value={search} onChange={e=>setSearch(e.target.value)} /></div><div className="table-responsive"><table className="table align-middle mb-0"><thead className="table-light"><tr><th className="ps-4">Student</th><th>Route</th><th>Vehicle</th><th>Stop</th><th>Trip</th><th className="text-end pe-4">Action</th></tr></thead><tbody>{assignments.map(item=><tr key={item.id}><td className="ps-4"><strong>{nameOf(item.student)}</strong><div className="small text-muted">{item.student.reg_no||item.student.email}</div></td><td>{item.route.name}</td><td>{item.vehicle.registration_number}</td><td>{item.stop?.name||"—"}</td><td className="text-capitalize">{item.trip_type}</td><td className="text-end pe-4"><button className="btn btn-sm btn-outline-danger" disabled={saving} onClick={()=>window.confirm("End this transport assignment?")&&run(()=>transportApi.endAssignment(item.id),"Transport assignment ended.")}>End</button></td></tr>)}{!loading&&!assignments.length&&<tr><td colSpan={6} className="text-center text-muted py-5">No active transport assignments.</td></tr>}</tbody></table></div></div>
  </main></div></div></>;
}
