import { useEffect, type ReactNode } from "react";
import { Link } from "react-router-dom";
import "./LegalPage.css";

type Section = { id: string; title: string; content: ReactNode };

function LegalPage({ title, intro, sections }: { title: string; intro: string; sections: Section[] }) {
  useEffect(() => {
    document.title = `${title} | GradeQuest`;
    window.scrollTo(0, 0);
  }, [title]);

  return <div className="legal-page">
    <header className="legal-header">
      <div className="legal-shell">
        <nav className="legal-nav" aria-label="Legal page navigation">
          <Link className="legal-brand" to="/" aria-label="GradeQuest homepage"><img src="/media/logo/gradequest-logo.png" alt="GradeQuest" /></Link>
          <Link className="legal-home" to="/">Back to homepage</Link>
        </nav>
        <div className="legal-hero"><span className="legal-kicker">Legal</span><h1>{title}</h1><p>{intro}</p></div>
      </div>
    </header>
    <main className="legal-shell legal-layout">
      <aside className="legal-toc" aria-label="On this page"><strong>On this page</strong>{sections.map(section => <a key={section.id} href={`#${section.id}`}>{section.title}</a>)}</aside>
      <article className="legal-content">
        <div className="legal-notice"><strong>Effective date:</strong> 9 August 2026. This document applies to GradeQuest websites, applications, portals, and related services.</div>
        {sections.map(section => <section className="legal-section" id={section.id} key={section.id}><h2>{section.title}</h2>{section.content}</section>)}
      </article>
    </main>
    <footer className="legal-footer"><div className="legal-shell legal-footer-inner"><span>© {new Date().getFullYear()} GradeQuest, a product of Samaritan Technologies.</span><span><Link to="/privacy-policy">Privacy Policy</Link> · <Link to="/terms-and-conditions">Terms & Conditions</Link></span></div></footer>
  </div>;
}

export function PrivacyPolicyPage() {
  const sections: Section[] = [
    { id: "who-we-are", title: "1. Who we are", content: <><p>GradeQuest is a school-management platform operated by Samaritan Technologies (“GradeQuest”, “we”, “us” or “our”). Schools use the platform to manage academic and administrative activities.</p><p>For most student, parent, teacher and staff records entered by a school, the school decides why and how the information is used and acts as the data controller. GradeQuest processes that information for the school as its technology service provider. For account, billing, support, security and website information that we collect for our own operations, GradeQuest acts as the data controller.</p></> },
    { id: "data", title: "2. Information we collect", content: <><p>Depending on the features a school enables, we may process:</p><ul><li>identity and profile information, including names, photographs, dates of birth, gender, admission or staff identifiers;</li><li>contact and account information, including email, phone number, address, role and login credentials;</li><li>school and academic records, including class, attendance, subjects, assessments, grades, report cards, behavioural records and CBT responses;</li><li>parent or guardian relationships and communication preferences;</li><li>financial and operational records, including fee schedules, invoices, payment status, receipts and transaction references. Payment card details are handled by the relevant payment provider and are not intended to be stored by GradeQuest;</li><li>optional records used by enabled modules, such as hostel, transport, staff attendance, location or biometric-related attendance identifiers;</li><li>support messages, demo requests, feedback and communications; and</li><li>technical information such as IP address, device/browser data, login events, audit logs, cookies and service usage.</li></ul></> },
    { id: "use", title: "3. How we use information", content: <><p>We use information to provide and administer GradeQuest; authenticate users; calculate and publish results; manage fees, attendance, CBT, communications and other requested modules; process subscriptions; provide support; secure, troubleshoot and improve the service; maintain audit records; comply with law; and send service notices. Marketing messages are sent only where permitted, and recipients may opt out.</p><p>We do not sell personal information. We do not use a school’s confidential student data to advertise to students or parents.</p></> },
    { id: "basis", title: "4. Legal grounds", content: <p>Where applicable, processing is based on performance of a contract, compliance with legal obligations, legitimate interests such as security and service improvement, consent, or another lawful basis available under the Nigeria Data Protection Act 2023 and other applicable laws. Schools are responsible for establishing an appropriate lawful basis and providing required notices for data they upload.</p> },
    { id: "children", title: "5. Children’s information", content: <><p>GradeQuest is designed for educational institutions and may process information about children on a school’s instructions. Schools and guardians remain responsible for the notices, permissions and safeguards required for children’s data. Children should not create an account or submit information except through, or with authorization from, their school or parent/guardian.</p><p>We apply access controls appropriate to user roles and do not knowingly use children’s school records for behavioural advertising.</p></> },
    { id: "sharing", title: "6. Sharing and service providers", content: <><p>We may share only the information needed with authorized school users; a student’s parent or guardian; hosting, email, messaging, analytics, support and infrastructure providers; payment processors; professional advisers; authorities where legally required; or a successor in a legitimate business transaction.</p><p>Schools control their own users and permissions. Some modules may connect to third-party services such as payment gateways or messaging providers. Their own privacy terms also apply when they process information independently.</p></> },
    { id: "transfers", title: "7. Storage and international transfers", content: <p>Information may be stored or processed in Nigeria or other countries where our vetted service providers operate. Where data is transferred across borders, we use safeguards required by applicable data-protection law and require providers to protect it appropriately.</p> },
    { id: "retention", title: "8. Data retention", content: <p>We retain personal information only for as long as needed to provide the service, meet contractual and legal obligations, resolve disputes, prevent fraud and maintain required records. Retention varies by record type and the school’s instructions. After account closure, information may remain in restricted backups for a limited period before secure deletion. Schools should export records they are legally required to preserve before ending the service.</p> },
    { id: "security", title: "9. Security", content: <p>We use reasonable administrative, technical and organizational safeguards, including access controls, authentication, logging, backups and encryption where appropriate. No online system is completely secure. Schools must protect administrator credentials, configure roles correctly and notify us promptly of suspected unauthorized access.</p> },
    { id: "rights", title: "10. Your rights", content: <><p>Subject to applicable law, you may request access, correction, deletion, restriction, portability, withdrawal of consent, or objection to certain processing. You may also complain to the Nigeria Data Protection Commission.</p><p>If your information was supplied by a school, contact the school first because it controls the record. We will assist the school with a valid request. For information controlled by GradeQuest, contact <a href="mailto:support@gradequest.com.ng">support@gradequest.com.ng</a>. We may verify your identity before acting.</p></> },
    { id: "cookies", title: "11. Cookies and similar technologies", content: <p>We use essential browser storage and cookies for login sessions, security and core functionality. We may use limited analytics to understand service performance. You can control non-essential cookies through available consent controls or browser settings, but disabling essential storage may prevent the service from working.</p> },
    { id: "changes", title: "12. Changes and contact", content: <><p>We may update this policy as the service or law changes. Material changes will be communicated through the platform, by email or on this page, and the effective date will be revised.</p><p>Questions, complaints and privacy requests may be sent to <a href="mailto:support@gradequest.com.ng">support@gradequest.com.ng</a>. Schools may also use their GradeQuest support channel.</p></> },
  ];
  return <LegalPage title="Privacy Policy" intro="How GradeQuest collects, uses, protects and manages information for schools, students, parents and platform users." sections={sections} />;
}

export function TermsAndConditionsPage() {
  const sections: Section[] = [
    { id: "agreement", title: "1. Agreement and eligibility", content: <><p>These Terms & Conditions (“Terms”) govern access to GradeQuest. By creating an account, signing an order, paying for a subscription or using the service, the school or organization (“Customer”) and its authorized users agree to these Terms.</p><p>The person accepting these Terms for a Customer confirms that they have authority to bind that Customer. Users must provide accurate information and be legally capable of using the service. If you do not agree, do not use GradeQuest.</p></> },
    { id: "service", title: "2. The GradeQuest service", content: <p>GradeQuest provides hosted school-management tools that may include student and staff records, grading, results, fees, attendance, CBT, parent communication, analytics and other subscribed modules. Features, limits and support levels depend on the selected plan or written order. We may improve or modify the service, provided we do not materially remove paid core functionality during a current subscription without reasonable notice.</p> },
    { id: "accounts", title: "3. Accounts and school responsibilities", content: <><p>The Customer is responsible for its users, data accuracy, role assignments, password security, lawful instructions and all activity under its accounts. The Customer must promptly remove access for users who leave or change roles and notify us of suspected compromise.</p><p>The Customer is responsible for obtaining required permissions and providing legally required notices before adding student, parent, employee or other personal information. GradeQuest is not the official custodian of records that a school is legally required to retain; schools should maintain appropriate exports and records.</p></> },
    { id: "acceptable-use", title: "4. Acceptable use", content: <><p>You must not use GradeQuest to break the law, violate another person’s rights, upload malicious code, attempt unauthorized access, disrupt the service, bypass plan limits, scrape or reverse engineer the platform, share accounts improperly, send unlawful or unsolicited communications, or store content unrelated to legitimate school operations.</p><p>You must not use automated or AI-enabled features as the sole basis for high-impact decisions about a student or employee without appropriate human review. We may investigate misuse and restrict access where reasonably necessary to protect users or the service.</p></> },
    { id: "fees", title: "5. Subscriptions, fees and taxes", content: <><p>Paid access is billed according to the selected plan, invoice or order. Fees, billing periods, user/student limits, renewal rules and any trial terms shown at purchase form part of these Terms. Unless the applicable order states otherwise, fees are due in advance and do not include taxes or third-party transaction charges.</p><p>Failure to pay may result in restricted features, suspension or non-renewal after applicable notices. Fees already earned are non-refundable except where required by law or expressly stated in the applicable billing or refund policy. Price changes apply from the next renewal after reasonable notice.</p></> },
    { id: "data", title: "6. Customer data and privacy", content: <><p>The Customer retains its rights in information and content it submits (“Customer Data”). The Customer grants us the limited right to host, copy, transmit, back up and otherwise process Customer Data only to provide, secure, support and improve the service, comply with law and fulfil these Terms.</p><p>Our <Link to="/privacy-policy">Privacy Policy</Link> explains our data practices. Where GradeQuest processes personal data for a school, the parties will comply with applicable data-protection obligations and any separate data-processing agreement.</p></> },
    { id: "third-party", title: "7. Third-party services", content: <p>Optional integrations, payment gateways, messaging networks and external links are provided by third parties. Their availability, fees and terms are outside our control. The Customer authorizes us to exchange the data necessary to operate an integration it enables. We are not responsible for an independent third party’s service, but we will use reasonable care when selecting providers we engage directly.</p> },
    { id: "ip", title: "8. Intellectual property and feedback", content: <><p>GradeQuest, its software, design, documentation, trademarks and underlying technology belong to Samaritan Technologies or its licensors. These Terms grant only a limited, non-exclusive, non-transferable right to use the service during an active subscription.</p><p>You may provide feedback. We may use it without restriction or payment, provided we do not publicly identify you or disclose confidential Customer Data without permission.</p></> },
    { id: "availability", title: "9. Availability, support and changes", content: <p>We aim to provide a reliable service but do not promise uninterrupted or error-free operation unless a signed service-level agreement says otherwise. Maintenance, internet failures, third-party outages, emergencies and events outside reasonable control may affect access. Support is provided according to the Customer’s plan and published support channels.</p> },
    { id: "suspension", title: "10. Suspension and termination", content: <><p>We may suspend access where fees are overdue, use creates a security or legal risk, these Terms are materially breached, or suspension is required by law. Where practical, we will give notice and an opportunity to remedy the issue.</p><p>Either party may end the service according to the subscription or order. On termination, the Customer’s right to use GradeQuest ends. The Customer should export its data before termination. We may delete Customer Data after a reasonable post-termination period, subject to law, backup cycles and agreed retention arrangements. Provisions that by nature should survive termination will survive.</p></> },
    { id: "warranties", title: "11. Disclaimers and liability", content: <><p>GradeQuest is a technology tool, not legal, accounting or educational advice. Schools remain responsible for reviewing results, fees, communications, AI-assisted output and administrative decisions before relying on them. Except for express commitments in these Terms or a signed order, the service is provided “as available” to the fullest extent permitted by law.</p><p>To the fullest extent permitted by law, neither party is liable for indirect, incidental, special or consequential loss, lost profit or lost data. GradeQuest’s total liability arising from the service will not exceed the fees paid by the Customer for the affected service in the twelve months before the event giving rise to the claim. This limitation does not apply where liability cannot legally be limited.</p></> },
    { id: "indemnity", title: "12. Indemnity", content: <p>The Customer will defend and indemnify GradeQuest against third-party claims arising from the Customer’s unlawful Customer Data, misuse of the service, violation of another person’s rights or breach of its data-protection responsibilities, except to the extent the claim was caused by GradeQuest’s breach, negligence or wilful misconduct.</p> },
    { id: "law", title: "13. Governing law and disputes", content: <p>These Terms are governed by the laws of the Federal Republic of Nigeria. The parties will first attempt in good faith to resolve a dispute through written notice and negotiation. If it is not resolved within 30 days, either party may pursue available remedies before a court of competent jurisdiction in Nigeria, unless a signed order provides a different lawful dispute process.</p> },
    { id: "general", title: "14. General terms and contact", content: <><p>Neither party may assign these Terms without the other’s consent, except in connection with a merger, reorganization or sale of substantially all relevant assets. If part of these Terms is unenforceable, the remaining terms continue. Delay in enforcement is not a waiver. A signed order and these Terms form the agreement for the service; the signed order controls if there is a direct conflict.</p><p>We may update these Terms for legal, security or service changes. Material changes will be notified reasonably before they take effect. Continued use after the effective date constitutes acceptance. Questions may be sent to <a href="mailto:support@gradequest.com.ng">support@gradequest.com.ng</a>.</p></> },
  ];
  return <LegalPage title="Terms & Conditions" intro="The rules governing access to and use of the GradeQuest school-management platform and its related services." sections={sections} />;
}
